FORMAT: 1A
HOST: http://private-2dd156-studentloanrepaymentapi.apiary-mock.com

# student-loan-repayment-api

API to get informatiob about repayments. When your projected last day should be and how to find missing informaton.

## Repayments [/repayments]

### Create a new repayment [POST]

You can create a new repayment info by subitting your known data.

+ Request (application/json)

        {
            "studyYears": [2008, 2009, 2010],
            "placementYear": 2010,
            "jobs": [
                {
                    "startDate": "2012-04-01T00:00:00.511Z",
                    "endDate": "2013-04-01T00:00:00.511Z",
                    "basicSalary": 30000
                }
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /repayments/1

    + Body

            {
                "lastRepaymentDate": "2023-04-01T00:00:00.511Z",
                "lastRepaymentSum": 24.5,
                "projectedMonthlyRepayment": 300.20,
                "totalLoan": 9125,
                "totalRepaid": 569.93
            }
            
            
## Repayments [/repayments/1/details]

### Get info on repayements [GET]

+ Response 200 (application/json)


    + Body

            [
                {
                    "date": "2008-10-01T00:00:00.511Z",
                    "total": "1000"
                    "interest": 45.44,
                    "repayedThisMonth": 0,
                    "newTotal": "1045.44",
                    "interestRate: 0.015
                },
                {
                    "date": "2008-11-01T00:00:00.511Z",
                    "total": "1045.44"
                    "interest": 45.44,
                    "repayedThisMonth": 0,
                    "newTotal": "1090.88",
                    "interestRate: 0.015
                }
            ]
            
## Repayments [/repayments/1/projections]

### Get info on repayements [GET]

+ Response 200 (application/json)


    + Body

            [
                {
                    "date": "2021-10-01T00:00:00.511Z",
                    "total": "1000"
                    "interest": 45.44,
                    "repayedThisMonth": 1000,
                    "newTotal": "1045.44",
                    "interestRate: 0.015
                },
                {
                    "date": "2021-11-01T00:00:00.511Z",
                    "total": "1045.44"
                    "interest": 45.44,
                    "repayedThisMonth": 0,
                    "newTotal": "1090.88",
                    "interestRate: 0.015
                }
            ]
            