FORMAT: 1A

# student-loan-repayment-api

API to get informatiob about repayments. When your projected last day should be and how to find missing informaton.

## Repayments [/repayments]

### Create a new repayment [POST]

You can create a new repayment info by subitting your known data.

+ Request (application/json)

        {
            "studyYears": [2008, 2009, 2011],
            "placementYear": 2010,
            "jobs": [
                {
                    startDate: "2012-04-01T00:00:00.511Z",
                    endDate: "2013-04-01T00:00:00.511Z",
                    basicSalary: 30000
                }
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /repayments

    + Body

            {
                "lastRepaymentDate": "2023-04-01T00:00:00.511Z",
                "lastRepaymentSum": 24.5,
                "projectedMonthlyRepayment": 300.20
            }
